"""Summary data from Nextcoud."""
from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime
from typing import Final

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntity,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.config_entries import ConfigEntry
from homeassistant.const import (
    PERCENTAGE,
    EntityCategory,
    UnitOfInformation,
    UnitOfTime,
)
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.util.dt import utc_from_timestamp

from .const import DOMAIN
from .coordinator import NextcloudDataUpdateCoordinator
from .entity import NextcloudEntity

UNIT_OF_LOAD: Final[str] = "load"


@dataclass(frozen=True)
class NextcloudSensorEntityDescription(SensorEntityDescription):
    """Describes Nextcloud sensor entity."""

    value_fn: Callable[[str | int | float], str | int | float | datetime] = (
        lambda value: value
    )


SENSORS: Final[list[NextcloudSensorEntityDescription]] = [
    NextcloudSensorEntityDescription(
        key="activeUsers_last1hour",
        REDACTED_VALUE"nextcloud_activeusers_last1hour",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="activeUsers_last24hours",
        REDACTED_VALUE"nextcloud_activeusers_last24hours",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="activeUsers_last5minutes",
        REDACTED_VALUE"nextcloud_activeusers_last5minutes",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="cache_expunges",
        REDACTED_VALUE"nextcloud_cache_expunges",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="cache_mem_size",
        REDACTED_VALUE"nextcloud_cache_mem_size",
        device_class=SensorDeviceClass.DATA_SIZE,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_display_precision=1,
        suggested_unit_of_measurement=UnitOfInformation.MEGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="cache_memory_type",
        REDACTED_VALUE"nextcloud_cache_memory_type",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="cache_num_entries",
        REDACTED_VALUE"nextcloud_cache_num_entries",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="cache_num_hits",
        REDACTED_VALUE"nextcloud_cache_num_hits",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="cache_num_inserts",
        REDACTED_VALUE"nextcloud_cache_num_inserts",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="cache_num_misses",
        REDACTED_VALUE"nextcloud_cache_num_misses",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="cache_num_slots",
        REDACTED_VALUE"nextcloud_cache_num_slots",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="cache_start_time",
        REDACTED_VALUE"nextcloud_cache_start_time",
        device_class=SensorDeviceClass.TIMESTAMP,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        value_fn=lambda val: utc_from_timestamp(float(val)),
    ),
    NextcloudSensorEntityDescription(
        key="cache_ttl",
        REDACTED_VALUE"nextcloud_cache_ttl",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="database_size",
        REDACTED_VALUE"nextcloud_database_size",
        device_class=SensorDeviceClass.DATA_SIZE,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_display_precision=1,
        suggested_unit_of_measurement=UnitOfInformation.MEGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="database_type",
        REDACTED_VALUE"nextcloud_database_type",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="database_version",
        REDACTED_VALUE"nextcloud_database_version",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="interned_strings_usage_buffer_size",
        REDACTED_VALUE"nextcloud_interned_strings_usage_buffer_size",
        device_class=SensorDeviceClass.DATA_SIZE,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_display_precision=1,
        suggested_unit_of_measurement=UnitOfInformation.MEGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="interned_strings_usage_free_memory",
        REDACTED_VALUE"nextcloud_interned_strings_usage_free_memory",
        device_class=SensorDeviceClass.DATA_SIZE,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_display_precision=1,
        suggested_unit_of_measurement=UnitOfInformation.MEGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="interned_strings_usage_number_of_strings",
        REDACTED_VALUE"nextcloud_interned_strings_usage_number_of_strings",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="interned_strings_usage_used_memory",
        REDACTED_VALUE"nextcloud_interned_strings_usage_used_memory",
        device_class=SensorDeviceClass.DATA_SIZE,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_display_precision=1,
        suggested_unit_of_measurement=UnitOfInformation.MEGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="jit_buffer_free",
        REDACTED_VALUE"nextcloud_jit_buffer_free",
        device_class=SensorDeviceClass.DATA_SIZE,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_display_precision=1,
        suggested_unit_of_measurement=UnitOfInformation.MEGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="jit_buffer_size",
        REDACTED_VALUE"nextcloud_jit_buffer_size",
        device_class=SensorDeviceClass.DATA_SIZE,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_display_precision=1,
        suggested_unit_of_measurement=UnitOfInformation.MEGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="jit_kind",
        REDACTED_VALUE"nextcloud_jit_kind",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="jit_opt_flags",
        REDACTED_VALUE"nextcloud_jit_opt_flags",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="jit_opt_level",
        REDACTED_VALUE"nextcloud_jit_opt_level",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="opcache_statistics_blacklist_miss_ratio",
        REDACTED_VALUE"nextcloud_opcache_statistics_blacklist_miss_ratio",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        native_unit_of_measurement=PERCENTAGE,
    ),
    NextcloudSensorEntityDescription(
        key="opcache_statistics_blacklist_misses",
        REDACTED_VALUE"nextcloud_opcache_statistics_blacklist_misses",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="opcache_statistics_hash_restarts",
        REDACTED_VALUE"nextcloud_opcache_statistics_hash_restarts",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="opcache_statistics_hits",
        REDACTED_VALUE"nextcloud_opcache_statistics_hits",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="opcache_statistics_last_restart_time",
        REDACTED_VALUE"nextcloud_opcache_statistics_last_restart_time",
        device_class=SensorDeviceClass.TIMESTAMP,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        value_fn=lambda val: utc_from_timestamp(float(val)),
    ),
    NextcloudSensorEntityDescription(
        key="opcache_statistics_manual_restarts",
        REDACTED_VALUE"nextcloud_opcache_statistics_manual_restarts",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="opcache_statistics_max_cached_keys",
        REDACTED_VALUE"nextcloud_opcache_statistics_max_cached_keys",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="opcache_statistics_misses",
        REDACTED_VALUE"nextcloud_opcache_statistics_misses",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="opcache_statistics_num_cached_keys",
        REDACTED_VALUE"nextcloud_opcache_statistics_num_cached_keys",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="opcache_statistics_num_cached_scripts",
        REDACTED_VALUE"nextcloud_opcache_statistics_num_cached_scripts",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="opcache_statistics_oom_restarts",
        REDACTED_VALUE"nextcloud_opcache_statistics_oom_restarts",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="opcache_statistics_opcache_hit_rate",
        REDACTED_VALUE"nextcloud_opcache_statistics_opcache_hit_rate",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        native_unit_of_measurement=PERCENTAGE,
        suggested_display_precision=1,
    ),
    NextcloudSensorEntityDescription(
        key="opcache_statistics_start_time",
        REDACTED_VALUE"nextcloud_opcache_statistics_start_time",
        device_class=SensorDeviceClass.TIMESTAMP,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        value_fn=lambda val: utc_from_timestamp(float(val)),
    ),
    NextcloudSensorEntityDescription(
        key="server_php_opcache_memory_usage_current_wasted_percentage",
        REDACTED_VALUE"nextcloud_server_php_opcache_memory_usage_current_wasted_percentage",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        native_unit_of_measurement=PERCENTAGE,
        suggested_display_precision=1,
    ),
    NextcloudSensorEntityDescription(
        key="server_php_opcache_memory_usage_free_memory",
        REDACTED_VALUE"nextcloud_server_php_opcache_memory_usage_free_memory",
        device_class=SensorDeviceClass.DATA_SIZE,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_display_precision=1,
        suggested_unit_of_measurement=UnitOfInformation.MEGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="server_php_opcache_memory_usage_used_memory",
        REDACTED_VALUE"nextcloud_server_php_opcache_memory_usage_used_memory",
        device_class=SensorDeviceClass.DATA_SIZE,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_display_precision=1,
        suggested_unit_of_measurement=UnitOfInformation.MEGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="server_php_opcache_memory_usage_wasted_memory",
        REDACTED_VALUE"nextcloud_server_php_opcache_memory_usage_wasted_memory",
        device_class=SensorDeviceClass.DATA_SIZE,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_display_precision=1,
        suggested_unit_of_measurement=UnitOfInformation.MEGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="server_php_max_execution_time",
        REDACTED_VALUE"nextcloud_server_php_max_execution_time",
        device_class=SensorDeviceClass.DURATION,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfTime.SECONDS,
    ),
    NextcloudSensorEntityDescription(
        key="server_php_memory_limit",
        REDACTED_VALUE"nextcloud_server_php_memory_limit",
        device_class=SensorDeviceClass.DATA_SIZE,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_display_precision=1,
        suggested_unit_of_measurement=UnitOfInformation.MEGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="server_php_upload_max_filesize",
        REDACTED_VALUE"nextcloud_server_php_upload_max_filesize",
        device_class=SensorDeviceClass.DATA_SIZE,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_display_precision=1,
        suggested_unit_of_measurement=UnitOfInformation.MEGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="server_php_version",
        REDACTED_VALUE"nextcloud_server_php_version",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="server_webserver",
        REDACTED_VALUE"nextcloud_server_webserver",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="shares_num_fed_shares_sent",
        REDACTED_VALUE"nextcloud_shares_num_fed_shares_sent",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="shares_num_fed_shares_received",
        REDACTED_VALUE"nextcloud_shares_num_fed_shares_received",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="shares_num_shares",
        REDACTED_VALUE"nextcloud_shares_num_shares",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    NextcloudSensorEntityDescription(
        key="shares_num_shares_groups",
        REDACTED_VALUE"nextcloud_shares_num_shares_groups",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="shares_num_shares_link",
        REDACTED_VALUE"nextcloud_shares_num_shares_link",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="shares_num_shares_link_no_password",
        REDACTED_VALUE"nextcloud_shares_num_shares_link_no_password",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="shares_num_shares_mail",
        REDACTED_VALUE"nextcloud_shares_num_shares_mail",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="shares_num_shares_room",
        REDACTED_VALUE"nextcloud_shares_num_shares_room",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="shares_num_shares_user",
        REDACTED_VALUE"nextcloud_shares_num_shares_user",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="sma_avail_mem",
        REDACTED_VALUE"nextcloud_sma_avail_mem",
        device_class=SensorDeviceClass.DATA_SIZE,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_display_precision=1,
        suggested_unit_of_measurement=UnitOfInformation.MEGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="sma_num_seg",
        REDACTED_VALUE"nextcloud_sma_num_seg",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="sma_seg_size",
        REDACTED_VALUE"nextcloud_sma_seg_size",
        device_class=SensorDeviceClass.DATA_SIZE,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_display_precision=1,
        suggested_unit_of_measurement=UnitOfInformation.MEGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="storage_num_files",
        REDACTED_VALUE"nextcloud_storage_num_files",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    NextcloudSensorEntityDescription(
        key="storage_num_storages",
        REDACTED_VALUE"nextcloud_storage_num_storages",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    NextcloudSensorEntityDescription(
        key="storage_num_storages_home",
        REDACTED_VALUE"nextcloud_storage_num_storages_home",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="storage_num_storages_local",
        REDACTED_VALUE"nextcloud_storage_num_storages_local",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="storage_num_storages_other",
        REDACTED_VALUE"nextcloud_storage_num_storages_other",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    NextcloudSensorEntityDescription(
        key="storage_num_users",
        REDACTED_VALUE"nextcloud_storage_num_users",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    NextcloudSensorEntityDescription(
        key="system_apps_num_installed",
        REDACTED_VALUE"nextcloud_system_apps_num_installed",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    NextcloudSensorEntityDescription(
        key="system_apps_num_updates_available",
        REDACTED_VALUE"nextcloud_system_apps_num_updates_available",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    NextcloudSensorEntityDescription(
        key="system_cpuload_1",
        REDACTED_VALUE"nextcloud_system_cpuload_1",
        native_unit_of_measurement=UNIT_OF_LOAD,
        suggested_display_precision=2,
    ),
    NextcloudSensorEntityDescription(
        key="system_cpuload_5",
        REDACTED_VALUE"nextcloud_system_cpuload_5",
        native_unit_of_measurement=UNIT_OF_LOAD,
        suggested_display_precision=2,
    ),
    NextcloudSensorEntityDescription(
        key="system_cpuload_15",
        REDACTED_VALUE"nextcloud_system_cpuload_15",
        native_unit_of_measurement=UNIT_OF_LOAD,
        suggested_display_precision=2,
    ),
    NextcloudSensorEntityDescription(
        key="system_freespace",
        REDACTED_VALUE"nextcloud_system_freespace",
        device_class=SensorDeviceClass.DATA_SIZE,
        native_unit_of_measurement=UnitOfInformation.BYTES,
        suggested_display_precision=2,
        suggested_unit_of_measurement=UnitOfInformation.GIGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="system_mem_free",
        REDACTED_VALUE"nextcloud_system_mem_free",
        device_class=SensorDeviceClass.DATA_SIZE,
        native_unit_of_measurement=UnitOfInformation.KILOBYTES,
        suggested_display_precision=2,
        suggested_unit_of_measurement=UnitOfInformation.GIGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="system_mem_total",
        REDACTED_VALUE"nextcloud_system_mem_total",
        device_class=SensorDeviceClass.DATA_SIZE,
        native_unit_of_measurement=UnitOfInformation.KILOBYTES,
        suggested_display_precision=2,
        suggested_unit_of_measurement=UnitOfInformation.GIGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="system_memcache.distributed",
        REDACTED_VALUE"nextcloud_system_memcache_distributed",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="system_memcache.local",
        REDACTED_VALUE"nextcloud_system_memcache_local",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="system_memcache.locking",
        REDACTED_VALUE"nextcloud_system_memcache_locking",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    NextcloudSensorEntityDescription(
        key="system_swap_total",
        REDACTED_VALUE"nextcloud_system_swap_total",
        device_class=SensorDeviceClass.DATA_SIZE,
        native_unit_of_measurement=UnitOfInformation.KILOBYTES,
        suggested_display_precision=2,
        suggested_unit_of_measurement=UnitOfInformation.GIGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="system_swap_free",
        REDACTED_VALUE"nextcloud_system_swap_free",
        device_class=SensorDeviceClass.DATA_SIZE,
        native_unit_of_measurement=UnitOfInformation.KILOBYTES,
        suggested_display_precision=2,
        suggested_unit_of_measurement=UnitOfInformation.GIGABYTES,
    ),
    NextcloudSensorEntityDescription(
        key="system_theme",
        REDACTED_VALUE"nextcloud_system_theme",
    ),
    NextcloudSensorEntityDescription(
        key="system_version",
        REDACTED_VALUE"nextcloud_system_version",
    ),
]


async def async_setup_entry(
    hass: HomeAssistant, entry: ConfigEntry, async_add_entities: AddEntitiesCallback
) -> None:
    """Set up the Nextcloud sensors."""
    coordinator: NextcloudDataUpdateCoordinator = hass.data[DOMAIN][entry.entry_id]
    async_add_entities(
        NextcloudSensor(coordinator, entry, sensor)
        for sensor in SENSORS
        if sensor.key in coordinator.data
    )


class NextcloudSensor(NextcloudEntity, SensorEntity):
    """Represents a Nextcloud sensor."""

    entity_description: NextcloudSensorEntityDescription

    @property
    def native_value(self) -> str | int | float | datetime:
        """Return the state for this sensor."""
        val = self.coordinator.data.get(self.entity_description.key)
        return self.entity_description.value_fn(val)  # type: ignore[arg-type]
