add_bonus_time:
  fields:
    bonus_time:
      required: true
      example: 30
      selector:
        number:
          min: -1
          max: 1440
          unit_of_measurement: minutes
          mode: box
    device_id:
      required: true
      example: REDACTED_VALUE
      selector:
        device:
          integration: nintendo_parental_controls
